BEGIN TRANSACTION;
CREATE TABLE users (uid INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, username TEXT NOT NULL UNIQUE, password TEXT NOT NULL UNIQUE);
INSERT INTO "users" VALUES(0,'test','a94a8fe5ccb19ba61c4c0873d391e987982fbbd3');
CREATE TABLE data (pid INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, time INTEGER NOT NULL, dir TEXT NOT NULL, source INTEGER NOT NULL, sport INTEGER NOT NULL, dest INTEGER NOT NULL, dport INTEGER NOT NULL, data TEXT NOT NULL);
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('users',0);
INSERT INTO "sqlite_sequence" VALUES('data',0);
COMMIT;
